#===================================================
# Docker VsCode Server
#
# Build:
# >>> podman build -t <IMAGE_NAME> -f <DOCKERFILE>
#
# Run:
# >>> podman run --rm --detach --publish 8080:8080 <IMAGE_NAME>
#
# Description:
# [x] Adds VsCode server
#
# References:
# * https://github.com/coder/code-server
#====================================================

FROM ubuntu:24.04

# Common packages
RUN apt-get -y update &&\
    apt-get -y upgrade &&\
    apt-get -y install \
    curl &&\
    apt-get -y clean

RUN curl -fsSL https://code-server.dev/install.sh | sh

EXPOSE 8080

# code-server by default runs on 127.0.0.1 (only reachable inside the container).
ENTRYPOINT ["code-server", "--auth", "none", "--bind-addr", "0.0.0.0:8080"]

# Connect to the VsCode server using:
# localhost:8080
