#===================================================
# Selkies Desktop
#
# Build:
# >>> podman build -t <IMAGE_NAME> -f <DOCKERFILE>
#
# Run:
# >>> 
#   podman run \
#     --name egl \
#     -it \
#     --detach \
#     --tmpfs /dev/shm:rw \
#     -e TZ=UTC \
#     -e DISPLAY_SIZEW=1920 \
#     -e DISPLAY_SIZEH=1080 \
#     -e DISPLAY_REFRESH=60 \
#     -e DISPLAY_DPI=96 \
#     -e DISPLAY_CDEPTH=24 \
#     -e SELKIES_ENCODER=nvh264enc \
#     -e SELKIES_VIDEO_BITRATE=8000 \
#     -e SELKIES_FRAMERATE=60 \
#     -e SELKIES_AUDIO_BITRATE=128000 \
#     -e SELKIES_ENABLE_BASIC_AUTH=false \
#     -p 8080:8080 \
#     -p 3478:3478 \
#     -p 3478:3478/udp \
#     ghcr.io/selkies-project/nvidia-egl-desktop:latest
#
# Description:
#   Plasma KDE desktop inside the container is reachable via `localhost:8080`.
#
# References:
# * https://github.com/selkies-project/docker-selkies-egl-desktop
#====================================================

FROM ghcr.io/selkies-project/nvidia-egl-desktop:24.04

# Common packages
RUN apt -y update &&\ 
    apt -y upgrade &&\
    apt -y install \
    neofetch &&\
    apt -y clean