#===================================================
# VsCodium Server
#
# Build:
# >>> podman build -t <IMAGE_NAME> -f <DOCKERFILE>
#
# Run:
# >>> podman run --rm --publish 8000:8000 <IMAGE_NAME>
#
#
# Description:
# [x] Adds VsCodium web server
#
# References:
# * https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo
#====================================================

FROM ubuntu:24.04

# Common packages
RUN apt-get -y update &&\
    apt-get -y upgrade &&\
    apt-get -y install \
    curl &&\
    apt-get -y clean

RUN curl -fsSL https://github.com/destin-v/codium-installer/raw/refs/heads/main/codium-install.sh | sh

# If your machine is behind the corporate firewall or proxy:
# RUN echo 'Acquire { https::Verify-Peer false }' >>/etc/apt/apt.conf.d/99verify-peer.conf

# Codium has a web server that can be used in the browser:
# WARNING: Connection is unsecured, only use if connection is secure through other means.
USER ubuntu 
EXPOSE 8000
ENTRYPOINT ["codium", "serve-web", "--host", "0.0.0.0",  "--port", "8000", "--without-connection-token"]