#===================================================
# VsCodium Server
#
# Build:
# >>> podman build -t <IMAGE_NAME> -f <DOCKERFILE>
#
# Run:
# >>> podman run --rm --publish 8000:8000 <IMAGE_NAME>
#
#
# Description:
# [x] Adds VsCodium web server
#
# References:
# * https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo
#====================================================

FROM ubuntu:24.04

# Common packages
RUN apt-get -y update &&\
    apt-get -y upgrade &&\
    apt-get -y install \
    gpg \
    wget &&\
    apt-get -y clean

# Add the Paul's GPG key of the repository:
RUN wget https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg \
-O /usr/share/keyrings/vscodium-archive-keyring.asc

# Add the repository:
RUN echo 'deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/vscodium-archive-keyring.asc ] https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs vscodium main' \
    | tee /etc/apt/sources.list.d/vscodium.list

# Install VsCodium
RUN apt-get -y update &&\
    apt-get -y install codium &&\
    apt-get -y clean

# If your machine is behind the corporate firewall or proxy:
# RUN echo 'Acquire { https::Verify-Peer false }' >>/etc/apt/apt.conf.d/99verify-peer.conf

# Codium has a web server that can be used in the browser:
# WARNING: Connection is unsecured, only use if connection is secure through other means.
USER ubuntu 
EXPOSE 8000
ENTRYPOINT ["codium", "serve-web", "--host", "0.0.0.0",  "--port", "8000", "--without-connection-token"]