#===================================================
# Docker X11 Display Forwarding
#
# Build:
# >>> podman build -t <IMAGE_NAME> -f <DOCKERFILE>
#
# Run:
# >>> podman run --rm --net=host --env="DISPLAY" --volume="$HOME/.Xauthority:/root/.Xauthority:rw" <IMAGE_NAME>
#
# Description:
# [x] Adds x11-apps
#
# References:
# * https://dzone.com/articles/docker-x11-client-via-ssh
#====================================================

FROM ubuntu:24.04

# Common packages
RUN apt-get -y update &&\
    apt-get -y upgrade &&\
    apt-get -y install \
    x11-apps &&\
    apt-get -y clean

ENTRYPOINT ["xeyes"]
